### ISSUE TITLE
GCPy updates for ND51-style diagnostics with 1D output in HISTORY

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#1]
- longitudes need to be in [0, 360)
- there should be an optional argument for specifiying the date (e.g. `python -m gcpy.1D_raveller --date '2019-07-01')

**Comment by LiamBindle** [comment]
@WilliamDowns Did we talk about this? I can't remember if you or I have already added this--do you know?

**Comment by WilliamDowns** [comment]
I don't remember discussing it. To clarify, is this only about adding the two bullet points in your original comment?

**Comment by LiamBindle** [comment]
I couldn't remember either. I'm hoping to have time to look at the 1D output in the next coupe days, and this issue just reminded me.

Yeah, they're both trivial updates. The initial raveller script I wrote had longitudes in [-180, 180) and the start date was fixed. I found these updates where necessary last time I tried the 1D output. I can add them!

**Comment by WilliamDowns** [comment]
Thanks!
