### ISSUE TITLE
Upstream MERRA2 data for September is missing

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#17]

**Comment by msulprizio** [comment]
Christoph Keller reported this during the GCSC telecon on 19 Nov 2020. He reported they found an issue and needed to do a rewind on MERRA-2 starting on 01 Sep 2020. He recommends downloading those fields again when they become available.

**Comment by LiamBindle** [comment]
@msulprizio Thanks, I missed that! I'll leave this open until that data is available.

**Comment by LiamBindle** [comment]
The MERRA2 fields for September are now available on ComputeCanada
