### ISSUE TITLE
Clarifying the stretched-grid parameter format requirements

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#19]
Right now `runConfig.sh` says:
- Minimum SF=1.0001 (this is correct)
- Target lat/lon must be floats (i.e. they must have a ".") --- I'm not positive if this is a hard requirement
- Target longitude must be in [0, 360) --- I'm not positive if this is a hard requirement either

Today I'll try to clarify these.

**Comment by msulprizio** [comment]
Do you also plan to provide example settings? For example, it might be nice to provide users with the settings to reproduce (as close as possible) the existing nested grid regions.

**Comment by LiamBindle** [comment]
I'm not exactly sure---I'd appreciate your thoughts on this. The thing that makes me hesitate is I'm trying to avoid anything that tends people towards thinking of stretched-grids as "nested grids for GCHP". I might be being pedantic, and perhaps it's inevitable people see them as that, but I'm trying to cast them as a new capability and their own thing. The reason is because there isn't a one-size-fits-all stretched-grid, for say North America, like there is for nested simulations. For example, one would want to use a more conservative stretch-factor if they were interested in CO in North America than if they were interested in surface-level NO2. (the stretched-grid manuscript provides guidance)

Stretched-grids have strengths and weaknesses compared to nested grids andWRF-GC, and that's definitely an important topic to communicate to users. I'm hesitant to give a list of parameter sets for grids similar to to nested grids because I think it frames grid-stretching the wrong way. 

I was thinking I would provide a stretched-grid tutorial (RTD, YouTube, and files on CCVM) for a stretched-grid simulation targetting the eastern US. I thought that would be a good example for demonstrating stretched-grids, and it would act a jumping-off point for people.

What do you think?

**Comment by msulprizio** [comment]
The tutorial may be good enough. Your reasoning makes sense. Also, the current nested grids are likely larger than most people need (e.g. the NA domain includes most of Canada, US, and Mexico when people may just be interested in a subset of that region). There's also differences between the nested grid region definitions for 0.25x0.3125 versus 0.5x0.625, and that was only done to save on computational resources.
