### ISSUE TITLE
Monthly/annual data input files for GCHPctm fixed---do we still need OFFLINE_LIGHTNING/v2020-11?

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#20]
geoschem/GCHPctm#62 should fix data input for fields with frequency <= 1 month. Recently, GCHPctm switched to OFFLINE_LIGHTNING/v2020-11 as a patch for this issue; but, now that there is a proper solution (geoschem/GCHPctm#62) do we still need this new dataset?

@msulprizio @yantosca @WilliamDowns What do you think?

**Comment by msulprizio** [comment]
We probably don't need the files in OFFLINE_LIGHTNING/v2020-11 anymore. It may be best to remove to avoid confusion. We should make sure we keep the script Lizzie used to create those files in case we need to do something similar in the future. We may eventually want to use daily files, but according to https://github.com/geoschem/geos-chem/issues/160 we should wait until we implement the capability to apply scale factors before regridding in HEMCO.
