### ISSUE TITLE
Procedures/guidelines for contributing to GEOS-Chem with the new submodule-based structure

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#23]
This afternoon @sdeastham and I were talking about the new submodule-based structure of GEOS-Chem, and some complications that arise for contributors.

A few procedures to help guide contributors might include:
1. How to set up a local development copy of GC-Classic or GCHP (i.e., forking submodules, updating submodule remotes, checking out submodule branches)
2. How to submit PRs
3. How to pull upstream geoschem updates into your local developement copy

These could be added to CONTRIBUTING.md. 

**Related issues**: 
- https://github.com/geoschem/GCHP/issues/66

**Comment by yantosca** [comment]
This could be the basis of a couple of tutorial videos.  I was thinking of doing a video about how to check out new branches after cloning so that people don't put stuff on detached HEAD states.  We can talk about this at our next GCST mtg.

**Comment by lizziel** [comment]
Are there any updates on this topic?

**Comment by lizziel** [comment]
Was anything done for this in the last few months? Today I got a request for guidelines on how users should handle submitting updates given use of submodules. @LiamBindle @yantosca

**Comment by yantosca** [comment]
Nothing done on this topic yet, @lizziel.

**Comment by LiamBindle** [comment]
I don't have any updates on this either. I think your recommendations in https://github.com/geoschem/GCHP/issues/66 are good advise for the community
