### ISSUE TITLE
Revise GitHub issue/PR templates?

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#26]
I heard that our issue/PR templates are a bit much. I agree too---they are a bit more comprehensive then they need to be. Streamlining the templates would
- encourage people to create issues (community involvement on GitHub)
- allow users to focus their efforts on describing the relevant details rather than filling out all the fields in the template.

For example, in our GCHP template we "require" all the configuration files. Most of these files aren't relevant, and they can be a pain to download since they aren't usually local.

Some examples of nice and clean issue templates:
- https://github.com/stevemao/github-issue-templates/blob/master/simple/ISSUE_TEMPLATE.md
- https://github.com/angular-translate/angular-translate/blob/master/.github/ISSUE_TEMPLATE.md

**Comment by yantosca** [comment]
We could try to simpilfy our issue templates.  That might be a good thing.

The only concern I have is that a lot of times we get issues from low-end users who describe the problem but do not give us any useful information as to what the problem was (no log files, etc.).  Also we need to know if they are running an "out-of-the-box" code or if they have made modifications.  (90% of the time it's their own modifications that lead to the bug.)

**Comment by LiamBindle** [comment]
Right, that makes sense. What do you think of using the stevemao template as a starting place, and expanding it with some GEOS-Chem specific sections like
- Log files (e.g. build log, or run log)
- Description of modifications to the code
- Software versions (compilers, NetCDF, MPI, etc.)


----

### GEOS-Chem version
Enter your GEOS-Chem version here.

### Description of the problem
Describe your problem problem here.

### Description of code modifications
Describe your code modifications here.

### Log files
- Build log (if applicable):
- Run log (if applicable):

### Software versions
- Compilers (Intel or GNU, and version):
- NetCDF version:
- MPI version:
- ESMF version:

**Comment by LiamBindle** [comment]
A section for "leads" or "what work you've done to troubleshoot it so far" would be a good addition.

Also a section for how to reproduce (if applicable)

**Comment by yantosca** [comment]
Thanks Liam.  I'll add that in.  I might just put the new template to the dev/13.0.0-final branch today

**Comment by LiamBindle** [comment]
Thanks, sounds good. Here's the template I pushed to GCHP yesterday. After this revision I was thinking of something like this

---

### Description of the problem
Describe your problem problem here. Describe the steps to reproduce the problem here, if possible.

### Description of troubleshooting performed
Describe any troubleshooting that you have already performed here. Also include any leads or suspicions here.

### GEOS-Chem version
Enter your GEOS-Chem version here.

### Description of code modifications
Describe your code modifications here.

### Log files
- Build log (if applicable):
- Run log (if applicable):
- Run script (if applicable):

### Software versions
- Compilers (Intel or GNU, and version):
- NetCDF version:
- MPI version:
- ESMF version:
---

Feel free to iterate!
