### ISSUE TITLE
Metfield processing backlog

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#31]
**MERRA2**
- [x] Nov, 2020
- [x] Dec, 2020

**GEOS-FP**
- [x] Dec, 2020
- [x] Jan, 2021

**Misc**
- [x] Follow up with Junjie when MERRA2 2020 is complete.

**Comment by YanshunLi-washu** [comment]
MERRA2 Nov, 2020, GEOS-FP Dec, 2020 and GEOS-FP Jan, 2021 were done processed on compute1. Waiting for instructions for transferring to CCVM. Details of summary are:

YEAR=2020 MONTH=11 ARCHIVE=MERRA2 ./summary
|============================================================| 
 Archive:                       MERRA2
 Month:                         2020-11 (30 days)
 Downloaded:                    300/300
 Processed 4x5:                 180/180
 Processed 2x2.5:               180/180
 Processed 0.5x0.625:           180/180
 Processed 0.5x0.625 (AS):      180/180
 Processed 0.5x0.625 (CH):      0/180
 Processed 0.5x0.625 (EU):      180/180
 Processed 0.5x0.625 (NA):      180/180
 Processed 0.25x0.3125:         0/180
 Processed 0.25x0.3125 (AS):    0/180
 Processed 0.25x0.3125 (CH):    0/180
 Processed 0.25x0.3125 (EU):    0/180
 Processed 0.25x0.3125 (NA):    0/180

YEAR=2020 MONTH=12 ARCHIVE=GEOSFP ./summary
|============================================================| 
 Archive:                       GEOSFP
 Month:                         2020-12 (31 days)
 Downloaded:                    4464/4464
 Processed 4x5:                 186/186
 Processed 2x2.5:               186/186
 Processed 0.5x0.625:           0/186
 Processed 0.5x0.625 (AS):      186/186
 Processed 0.5x0.625 (CH):      186/186
 Processed 0.5x0.625 (EU):      186/186
 Processed 0.5x0.625 (NA):      186/186
 Processed 0.25x0.3125:         186/186
 Processed 0.25x0.3125 (AS):    186/186
 Processed 0.25x0.3125 (CH):    186/186
 Processed 0.25x0.3125 (EU):    186/186
 Processed 0.25x0.3125 (NA):    186/186

|============================================================| 
 Archive:                       GEOSFP
 Month:                         2021-01 (31 days)
 Downloaded:                    4464/4464
 Processed 4x5:                 186/186
 Processed 2x2.5:               186/186
 Processed 0.5x0.625:           0/186
 Processed 0.5x0.625 (AS):      186/186
 Processed 0.5x0.625 (CH):      186/186
 Processed 0.5x0.625 (EU):      186/186
 Processed 0.5x0.625 (NA):      186/186
 Processed 0.25x0.3125:         186/186
 Processed 0.25x0.3125 (AS):    186/186
 Processed 0.25x0.3125 (CH):    186/186
 Processed 0.25x0.3125 (EU):    186/186
 Processed 0.25x0.3125 (NA):    186/186

MERRA2 Dec, 2020 is now in processing. Current status is:
|============================================================| 
 Archive:                       MERRA2
 Month:                         2020-12 (31 days)
 Downloaded:                    310/310
 Processed 4x5:                 79/186
 Processed 2x2.5:               79/186
 Processed 0.5x0.625:           79/186
 Processed 0.5x0.625 (AS):      79/186
 Processed 0.5x0.625 (CH):      0/186
 Processed 0.5x0.625 (EU):      79/186
 Processed 0.5x0.625 (NA):      79/186
 Processed 0.25x0.3125:         0/186
 Processed 0.25x0.3125 (AS):    0/186
 Processed 0.25x0.3125 (CH):    0/186
 Processed 0.25x0.3125 (EU):    0/186
 Processed 0.25x0.3125 (NA):    0/186

**Comment by LiamBindle** [comment]
Awesome! Nice work! Let me know when MERRA2 Dec 2020 finishes. I think we're still waiting on that new CCVM account.

**Comment by YanshunLi-washu** [comment]
Great! Will do

**Comment by YanshunLi-washu** [comment]
MERRA2 Dec 2020 is done now. Summary:
|============================================================| 
 Archive:                       MERRA2
 Month:                         2020-12 (31 days)
 Downloaded:                    310/310
 Processed 4x5:                 186/186
 Processed 2x2.5:               186/186
 Processed 0.5x0.625:           186/186
 Processed 0.5x0.625 (AS):      186/186
 Processed 0.5x0.625 (CH):      0/186
 Processed 0.5x0.625 (EU):      186/186
 Processed 0.5x0.625 (NA):      186/186

**Comment by LiamBindle** [comment]
Thanks @YanshunLi-washu! I started the transfers
