### ISSUE TITLE
Add GCHP documentation for History field aliases

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCST-internal#33]
There is the capability to assign aliases in GCHP history but we do not tap into that in GCHP. This is mainly because it might cause confusion to rename the export in the output file. However, we should include the capability in ours docs.

See also https://github.com/geoschem/geos-chem/issues/635 in which this functionality was relevant but unknown.

**Comment by lizziel** [comment]
@LiamBindle added documentation for configurating HISTORY.rc to [GCHP ReadTheDocs](https://gchp.readthedocs.io/en/latest/supplement/config-files/HISTORY.html). This information would be good to put there.

**Comment by LiamBindle** [comment]
Added the instructions for aliases to the docs for `fields`.

Latest docs: https://gchp.readthedocs.io/en/latest/supplement/config-files/HISTORY.html

Relevant commit: https://github.com/geoschem/GCHP/commit/4fed26163114b905aca3a09aff2dc8ea703d8449
