### ISSUE TITLE
GCHP runConfig.sh switch to turn off emissions does nothing

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCST-internal#36]
The emissions toggle in input.geos was removed in 13.0 but the corresponding switch to change it in runConfig.sh was not removed. Turning off emissions is now a bit more complicated. How to do it in GCHP needs to be assessed and runConfig.sh updated accordingly.

**Comment by msulprizio** [comment]
In case it helps with planning for GCHP... The idea is that we now control the emissions via the switch in HEMCO_Config.rc:

```
###############################################################################
### BEGIN SECTION EXTENSION SWITCHES
###############################################################################
# ExtNr ExtName                on/off  Species  Years avail.
0       Base                   : on    *
# ----- MAIN SWITCHES -----------------------------------------
    --> EMISSIONS              :       true
```

This controls reading in and therefore processing of emissions data in HEMCO standalone and GCClassic. In geoschem/GeosCore/hco_interface_gc_mod.F90 we also create a shadow variable `Input_Opt%DoEmissions` based on that switch to determine if emissions-related code in GEOS-Chem needs to be executed.

```
    !-----------------------------------------------------------------------
    ! EMISSIONS switch in HEMCO_Config.rc
    !
    ! Create a shadow field (Input_Opt%DoEmissions) to determine if
    ! emissions fluxes should be applied in mixing_mod.F90
    !-----------------------------------------------------------------------
    CALL GetExtOpt( HcoConfig, -999, 'EMISSIONS',           &
                    OptValBool=LTMP, FOUND=FOUND,  RC=HMRC )

    IF ( HMRC /= HCO_SUCCESS ) THEN
       RC     = HMRC
       ErrMsg = 'Error encountered in "GetExtOpt( EMISSIONS )"!'
       CALL GC_Error( ErrMsg, RC, ThisLoc, Instr )
       RETURN
    ENDIF
    IF ( .not. FOUND ) THEN
       ErrMsg = 'EMISSIONS not found in HEMCO_Config.rc file!'
       CALL GC_Error( ErrMsg, RC, ThisLoc )
       RETURN
    ENDIF
    Input_Opt%DoEmissions = LTMP
```

**Comment by lizziel** [comment]
Is there a way to also turn off all extensions?

**Comment by msulprizio** [comment]
No, not at the moment.

**Comment by lizziel** [comment]
Okay, when I update the switch in runConfig.sh I'll change the name to specify base emissions.
