### ISSUE TITLE
Old repos in geoschem organization that could be archived

### ISSUE THREAD

**Issue by LiamBindle** [geoschem/GCST-internal#43]
Hi all,

Today I was archiving some repos I created in the geoschem organization that aren't needed nowadays. I noticed some old repos that seem like they could be archived too.

I wasn't exactly sure what "archiving" did in practice, so here's the details from GitHub's docs: 

> Once a repository is archived, you cannot add or remove collaborators or teams. Contributors with access to the repository can only fork or star your project.
> 
> When a repository is archived, its issues, pull requests, code, labels, milestones, projects, wiki, releases, commits, tags, branches, reactions, code scanning alerts, and comments become read-only. To make changes in an archived repository, you must unarchive the repository first.

Essentially, it makes the repo read-only.

Based on that, I think the following repos could be archived
- https://github.com/geoschem/gcclassic-manpage-archive
- https://github.com/geoschem/gamap-manual
- https://github.com/geoschem/geos-chem-unittest
- https://github.com/geoschem/ncdfutil
- https://github.com/geoschem/gchp_legacy
- https://github.com/geoschem/MERRA2
- https://github.com/geoschem/CsGrid
- https://github.com/geoschem/geos-chem-docker
- https://github.com/geoschem/GEOS_FP
- https://github.com/geoschem/json-fortran
- https://github.com/geoschem/GEOSchem_GridComp
- https://github.com/geoschem/hemco_data_download
- https://github.com/geoschem/GEOSgcm_GridComp
- https://github.com/geoschem/Docker_GC
- https://github.com/geoschem/tempestremap
- https://github.com/geoschem/Singularity_GCHP
- https://github.com/geoschem/Singularity_GC

Are there any repos here that shouldn't be archived (made read-only)?

**Comment by lizziel** [comment]
Thanks @LiamBindle for doing this! GEOSgcm_GridComp and GEOSchem_GridComp can actually be deleted. I forked them a while ago but ended up doing development directly on the upstream since I was given permissions.

CsGrid is a fork of code developed by Seb. I'll check in with him on status of it. There was talk a while ago of putting some of it into GCPy. The upstream may still be active and we might want to develop on it.

**Comment by lizziel** [comment]
I'm reopening this issue since we should go through these and get status. @LiamBindle, how about we go through this list at the next GCST meeting?

**Comment by yantosca** [comment]
There was some discussion about having https://github.com/geoschem/ncdfutil be a submodule that could be pulled into GCClassic and HEMCO.  Perhaps keep this one for now.

Also https://github.com/geoschem/gcclassic-manpage-archive is serving the manual pages for older versions of GC (which some folks that use the GCClassic adjoint need).  Keep this one for now.

**Comment by msulprizio** [comment]
Based on discussion at our GCST meeting today, we can safely archive the following repos:

- https://github.com/geoschem/geos-chem-unittest
- https://github.com/geoschem/gchp_legacy
- https://github.com/geoschem/CsGrid
- https://github.com/geoschem/geos-chem-docker
- https://github.com/geoschem/json-fortran
- https://github.com/geoschem/GEOSchem_GridComp
- https://github.com/geoschem/GEOSgcm_GridComp
- https://github.com/geoschem/Docker_GC
- https://github.com/geoschem/tempestremap
- https://github.com/geoschem/Singularity_GCHP
- https://github.com/geoschem/Singularity_GC

The following met field repos are outdated. We should either update these or archive them and transfer over the currently used repos from WashU.
- https://github.com/geoschem/GEOS_FP
- https://github.com/geoschem/MERRA2


The following repos should remain for now:
- https://github.com/geoschem/ncdfutil
- https://github.com/geoschem/gcclassic-manpage-archive
- https://github.com/geoschem/gamap-manual
- https://github.com/geoschem/hemco_data_download

**Comment by yantosca** [comment]
I have archived the GEOS_FP and MERRA2 repos here.

**Comment by yantosca** [comment]
All of these repositories have now been archived.  
- https://github.com/geoschem/geos-chem-unittest
- https://github.com/geoschem/gchp_legacy
- https://github.com/geoschem/CsGrid
- https://github.com/geoschem/geos-chem-docker
- https://github.com/geoschem/json-fortran
- https://github.com/geoschem/GEOSchem_GridComp
- https://github.com/geoschem/GEOSgcm_GridComp
- https://github.com/geoschem/Docker_GC
- https://github.com/geoschem/tempestremap
- https://github.com/geoschem/Singularity_GCHP
- https://github.com/geoschem/Singularity_GC

**Comment by yantosca** [comment]
We can close this issue now.
