### ISSUE TITLE
GCHP seg faults if compiled with ifort and OMP=OFF

### ISSUE THREAD

**Issue by lizziel** [geoschem/GCST-internal#5]
GCHP seg faults during run-time after the merge of https://github.com/geoschem/GCHPctm/pull/50 if using an Intel compiler. This update went in during development of GCHP 13.0.0-alpha.13. I have not run into any issues with disabling OMP when using GNU compilers.

The problem appears to be an issue in MAPL when using Intel compilers with OMP turned off. The traceback can be found by enabling debug flags. I have not seen this issue before.
```
forrtl: severe (408): fort: (3): Subscript #1 of the array ELEMENTS has value 0 which is less than the lower bound of 1

Image              PC                Routine            Line        Source             
geos               0000000008DD3300  Unknown               Unknown  Unknown
geos               000000000712724B  mapl_meternodesta         179  vector_impl.inc
geos               0000000007171306  mapl_baseprofiler         159  BaseProfiler.F90
geos               00000000062314D9  mapl_genericmod_m        1841  MAPL_Generic.F90
geos               00000000077F7E29  Unknown               Unknown  Unknown
geos               00000000077FB9FB  Unknown               Unknown  Unknown
geos               00000000079FC5D5  Unknown               Unknown  Unknown
geos               00000000077F948A  Unknown               Unknown  Unknown
geos               0000000007FAA7C1  Unknown               Unknown  Unknown
geos               0000000007DE8EEF  Unknown               Unknown  Unknown
geos               000000000647EB28  mapl_capgridcompm         554  MAPL_CapGridComp.F90
geos               00000000077F7E29  Unknown               Unknown  Unknown
geos               00000000077FB9FB  Unknown               Unknown  Unknown
geos               00000000079FC5D5  Unknown               Unknown  Unknown
geos               00000000077F948A  Unknown               Unknown  Unknown
geos               0000000007FAA7C1  Unknown               Unknown  Unknown
geos               0000000007DE8EEF  Unknown               Unknown  Unknown
geos               000000000648DD95  mapl_capgridcompm         848  MAPL_CapGridComp.F90
```

Since we are trying to get the 13.0.0 benchmark going for the candidate release to the community I am adding a temporary fix as follows in the highest level CMakeLists.txt. We can try to address the underlying problem in MAPL prior to the official 13.0.0 release.
```
# Disable OMP by default if using gfortran to avoid a performance hit.
# Enable OMP if using ifort to avoid a run-time seg fault. Both of these issues
# are bugs under investigation.
if("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "GNU")
  set(OMP OFF CACHE BOOL "Switch to enable/disable OpenMP")
elseif("${CMAKE_Fortran_COMPILER_ID}" STREQUAL "Intel")
  set(OMP ON CACHE BOOL "Switch to enable/disable OpenMP")
endif()
```

**Comment by lizziel** [comment]
@LiamBindle, do you know the status of using intel compilers with OMP off? Do we have OMP off for all of GCHP now?

**Comment by LiamBindle** [comment]
It's turned off for the entirety of GEOS-Chem components. I think that some deep down MAPL parts might still have it enabled. 

I always use `OMP=OFF` and I'm not aware of any issues when it's off. I'm not sure if OMP=ON + intel still segfaults.

The default value is `OFF` (set [here](https://github.com/geoschem/GCHP/blob/106b8f783cafabd699e53beec3a4dd8aee45234b/CMakeLists.txt#L9)) so a user would have to explicitly turn it on to run into this. 

Maybe we should close this issue? I don't see a reason to add support for OMP=ON and there are plenty of other things to prioritize.
